name: Monitoring
on: [push]
#  schedule:
#  - cron: "1-59 * * * *"

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: matt-ball/newman-action@master
        with:
          collection: postman_collection.json
          environment: postman_environment.json
      - name: Launch newman
        run:  newman run https://www.getpostman.com/collections/631643-f695cab7-6878-eb55-7943-ad88e1ccfd65-JsLv
