name: Monitoring
on: [push]
#  schedule:
#  - cron: "*/1 * * * *"

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: matt-ball/newman-action@master
        with:
          collection: postman_collection.json
          environment: postman_environment.json
      - name: Success
        if: success()
        run: echo "ok"
      - name: Error
        if: failure()
        run: echo "Error"          
