name: Monitoring
on:
  schedule:
  - cron: "*/30 * * * *"

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: matt-ball/newman-action@0.1.7
        with:
          collection: postman_collection.json
          environment: postman_environment.json
      - name: Error
        if: failure()
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}    
          SLACK_MESSAGE: "ko"
          SLACK_COLOR: "#f44336"    
